sudo: false
language: python
python:
  - 2.7
env:
  - TRAVIS=true
install:
  - pip install -r requirements.txt
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.3.zip
  - unzip -o elasticsearch-1.7.3.zip &> /dev/null
script:
  - ./runtests.sh --cluster
after_success:
  coveralls
